import type React from 'react'

// PrivacyPolicyModal / TermsOfUseModal 공용 인라인 스타일 (GMC 테마 변수 사용)
// — Akademiya의 PrivacyPolicyModal.module.css 구조를 GMC 인라인 스타일 패턴으로 이식
export const policyModalStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.75)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
  },
  modal: {
    background: 'var(--card-bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-lg)',
    boxShadow: 'var(--shadow-lg)',
    width: '100%',
    maxWidth: '600px',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    padding: '20px 24px 14px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  title: {
    fontSize: '17px',
    fontWeight: 700,
    color: 'var(--text)',
    margin: '0 0 5px',
  },
  subtitle: {
    fontSize: '13px',
    color: 'var(--text-secondary, #9ca3af)',
    margin: '0 0 6px',
  },
  version: {
    fontSize: '11px',
    color: 'var(--text-secondary, #9ca3af)',
    background: 'var(--bg, #1e1e1e)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    padding: '2px 8px',
    display: 'inline-block',
  },
  content: {
    overflowY: 'auto',
    flex: 1,
    padding: '18px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  preamble: {
    fontSize: '12px',
    lineHeight: 1.7,
    color: 'var(--text-secondary, #9ca3af)',
    background: 'rgba(255,255,255,0.04)',
    borderRadius: 'var(--radius-sm)',
    padding: '10px 12px',
    margin: 0,
  },
  section: {
    borderTop: '1px solid var(--border)',
    paddingTop: '12px',
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--primary)',
    marginBottom: '7px',
    marginTop: 0,
  },
  sectionBody: {
    fontSize: '12px',
    lineHeight: 1.75,
    color: 'var(--text-secondary, #9ca3af)',
  },
  line: { margin: 0 },
  blank: { height: '7px', margin: 0 },
  // ── 재동의 변경 요약 표시용 (Akademiya 재동의 모달 패턴) ──
  summaryIntro: {
    fontSize: '12px',
    lineHeight: 1.7,
    color: 'var(--text)',
    background: 'rgba(255,255,255,0.04)',
    borderRadius: 'var(--radius-sm)',
    padding: '10px 12px',
    margin: 0,
  },
  changeList: {
    fontSize: '12px',
    lineHeight: 1.75,
    color: 'var(--text-secondary, #9ca3af)',
    margin: 0,
    paddingLeft: '18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  fullLink: {
    fontSize: '12px',
    color: 'var(--primary)',
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    textAlign: 'left',
    textDecoration: 'underline',
    alignSelf: 'flex-start',
  },
  footer: {
    padding: '14px 24px 18px',
    borderTop: '1px solid var(--border)',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  error: {
    fontSize: '12px',
    color: '#ef4444',
    margin: 0,
  },
  checkLabel: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    color: 'var(--text)',
    lineHeight: 1.5,
  },
  checkbox: {
    width: '15px',
    height: '15px',
    flexShrink: 0,
    marginTop: '1px',
    accentColor: 'var(--primary)',
    cursor: 'pointer',
  },
}
